# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 04a844d1a0d4f6c53eeb189da4eb87e17d2493d16752c8c088883a2e46096e55439b6bcf5b54cc9804404d6342ad0a1855523c71787b236449ebbfc43e18ce68

test:
  secret_key_base: b2f58637e6bcb2ecb27deeb59caacd3f1d906ec71774d521d58e5cb0fa71adf2d358d68b1b48b7b45c9c161ed9aabf20ec8289e9a65ecb48f00f07ab1cc4126f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
